exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vendor

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

sass:
  style: compressed
  sass_dir: _sass

ipaginate: 8 # jekyll-paginate > items per page
paginate_path: "/blog/page:num/" # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # base url for jekyll mentions

twitter:
  username: stuwilkins

author: Stuart Wilkins
title: Stuart Wilkins's Blog
email: stuart@stuwilkins.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stuwilkins.org" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: stuwilkins
github_username:  stuwilkins

theme: github-remote-theme
remote_theme: daviddarnes/alembic
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    #feature_image: "https://picsum.photos/2560/600?image=866"
    feature_image: "assets/images/IMG_0474.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Stuart Wilkins" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/bike2.png" # Site logo, also used in jekyll-seo-tag
description: "Stuart's Personal Website"
url: "https://stuwilkins.org"
baseurl: ""
repo: "https://github.com/stuwilkins/stuwilkins.github.io/"
email: "webmaster@stuwilkins.org"

css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

favicon_url: '/assets/logos/bike.ico'

# 9. Site navigation
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

navigation_footer:
  Adopted Alembic Theme: https://alembic.darn.es/

contact:
  github: https://github.com/stuwilkins
  strava: https://www.strava.com/athletes/4594992
  twitter: https://twitter.com/stuwilkins
  linkedin: https://www.linkedin.com/in/stuart-wilkins-69076627
  instagram: http://instagram.com/stuwilkins
  email: webmaster@stuwilkins.org

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
